### ISSUE TITLE
Qu: What font is used on the display?

### ISSUE THREAD

**Issue by CFD-designs** [lhm0/rotating_display#5]
I love this project. Was wondering if you might know what the default font is?
And how would you change it?
Thankyou.

**Comment by CFD-designs** [comment]
this should have gone under discussions - apologies

**Comment by lhm0** [comment]
I designed the fonts myself. Pixel by pixel, starting with a blank sheet of paper. This is real low level programming ;-)

Please have a look at file myBMP_templates.h. There you will find the bitmaps of the available fonts. In order to add a new font, you would need to design the bitmaps on a "by pixel" basis. It would be easy to design screens with new fonts by adding a new print function in "my_BMP.h" and "my_BMP.cpp". 

I am happy to support you with the implementation, if you are interested.

Make sure, you do not violate copyrights on fonts.

**Comment by CFD-designs** [comment]
Well done - that's dedication.
